### PR TITLE
remove unused refers when clean-ns

### PR DESCRIPTION
**Pull request by ericdallo**
fix-unused-refers

_this PR only remove the ns if all refers are unused, I'll implement the functionality for one or more unused later._

### CODE REVIEW

**Comment by ericdallo** [comment]
@snoe I didn't see any problem adding the `:declare` and `:alias` to the `:refer` tags, let me know what you think, it's kind of confusing for me what they mean truly.

**Comment by snoe** [comment]
I'm not sure that's right, some background:

There should only ever be one declaration (usage tagged `:declare`) for a thing in the project, so a referred symbol would be `:declare` inside the required ns.

An `:alias` tag is strictly for aliased namespaces and comes into play as the namespace portion of symbols and keywords. Marking the `refer` as `alias` would probably introduce some strange completion issues with the refer symbol being in the namespace slot.

**Comment by snoe** [comment]
So removing to remove refers you would probably need to ask crawler for unused-refers (or combine it with `unused-aliases`) and use it in [here](https://github.com/snoe/clojure-lsp/blob/master/src/clojure_lsp/refactor/transform.clj#L281)

**Comment by ericdallo** [comment]
I see, thanks for the great explanation @snoe, I'll try to find the refers together with the alias or combine like you said

**Comment by ericdallo** [comment]
@snoe I hope now it's ok

**Comment by snoe** [comment]
This is great, thanks!

**Pull request merged**
