### PR TITLE
Add workspace-symbol support

### PR DESCRIPTION
**Pull request by patrickpichler**
The lsp now supports the workspace symbol request. This allows to query
the whole workspace for a certain symbol and jump to it.

### CODE REVIEW

**Comment by patrickpichler** [comment]
The implementation might be a bit slow and naive. It might make sense to keep an index of all symbols cached somewhere.

**Comment by snoe** [comment]
I'm not too concerned with the speed, as long as clients aren't constantly hitting it. 

Do other implementations query with `starts-with`? I found it a bit surprising since it requires writing out the whole namespace. Is it too slow in your opinion if it's uses a substring match? (maybe if it returned nothing until 2 or 3 chars?)

**Comment by patrickpichler** [comment]
Yeah, the starts-with annoyes me now as well after using it for some time. I implemented it that way, because [eclipse JDT lsp](https://github.com/eclipse/eclipse.jdt.ls) uses it as well.

**Comment by snoe** [comment]
I love it! Thanks a ton.

**Pull request merged**
