### PR TITLE
Add support for shadow-cljs projects

### PR DESCRIPTION
**Pull request by dpsutton**
As far as I can tell, everything seems to work once a classpath is
established. There are three ways to do so with shadow depending on
tooling:

1. shadow-cljs is installed globally and can be called
2. it is run with npm as `npx shadow-cljs ...`
3. it is run with yarn as `yarn shadow-cljs ...`

So just test the system for which are present and go with that. Yarn
and npx have the ability to have all of their output silenced with
--quiet and --silent so all we get back are classpaths.

### CODE REVIEW

**Comment by snoe** [comment]
I don't think `exectuable-exists?` will work in windows.

This might be a case where we build in the most common or global command, but then ask users to specify their `:project-specs` in `.lsp/config.edn` (with a section in README).

**Comment by dpsutton** [comment]
> I don't think exectuable-exists? will work in windows.
Correct. I thought I saw some usage of other shell stuff that would prevent Windows as well so i thought i was embracing the current support.

Not sure which is the most likely to work. Depends if the user has the project configured with npm or yarn. Perhaps as a first step require shadow-cljs be installed globally which is probably a pretty safe bet at first.

**Comment by dpsutton** [comment]
Updated to rely on the globally installed version. Commit message has the way to configure if need to run under `npm` or `yarn`. Didn't see a great spot in the readme for it but didn't spend a ton of time thinking about it.

**Comment by snoe** [comment]
Thank you!

**Pull request merged**
